Added SolarEdge
ioBroker/modbus-templates pull request #2
Opened 2023-01-16 12:23 UTC by klein0r

2023-01-16 13:03 UTC, Apollon77 requested changes
Additionally: Any special non default settings needed?

2023-01-16 13:03 UTC, Apollon77 commented on PV-Wechselrichter/SolarEdge/README.md
> +## Weitere kompatible Sungrow Wechselrichter:
Typo? :-)

2023-01-16 13:47 UTC, klein0r commented on PV-Wechselrichter/SolarEdge/README.md
> +## Weitere kompatible Sungrow Wechselrichter:
Copy paste 😄

2023-01-16 13:55 UTC, klein0r commented
I would like to add another TSV file which includes further holding registers for an optional energy meter. How should I name that file?

2023-01-16 13:58 UTC, Apollon77 commented
I would say use "holding-registers-*.tsv" and add an info in the README which file contains what

2023-01-17 10:16 UTC, Apollon77 commented
Exactly, thank you!

2023-01-17 10:16 UTC, merged